# Created by Sean L. on Jun. 26.
# Last Updated by minc_nice_100 on Jun. 27.
# 
# Notepad - Backend
# .github/workflows/build-release.yaml
# 
# FeatherDev, 2025. All rights reserved.

name: Build and Push Image

on:
  push:
    branches: [main]

jobs:
  build:
    #runs-on: [self-hosted, Linux]
    runs-on: [ubuntu-latest]

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build and Push Image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/notepad-backend:latest
          # platforms: linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
